name: CI
on: [ push, pull_request ]
jobs:
  lint:
    # Don't run two jobs for a PR
    if: "${{ github.event_name == 'pull_request' || github.ref_name == 'main' }}"
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v3
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - uses: astral-sh/setup-uv@v6
      with:
        # We are using uv to install pre-commit, we don't have anything by default to cache
        # https://github.com/astral-sh/setup-uv
        cache-dependency-glob: ""
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit
      run: uv tool install pre-commit
    - run: just generate
    - run: just lint
      env:
        SKIP: actionlint
  test:
    # Don't run two jobs for a PR
    if: "${{ github.event_name == 'pull_request' || github.ref_name == 'main' }}"
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - "1.21"
        - "1.22"
        - "1.23"
        - "1.24"
    steps:
    - uses: extractions/setup-just@v3
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
    - name: Run tests
      # GOCOVERDIR sets the dir where `go run -cover` writes its coverage data too (i.e. from the instrumented generator binary)
      # And -test.gocoverdir sets where the tests write their coverage data to.
      #
      # And then `go tool covdata textfmt` merges the various sources in to the old style that tooling expects
      run: |
        mkdir -p covdata/unit/ covdata/gen/
        export GOCOVERDIR="$PWD/covdata/gen"
        just test -f github-actions --jsonfile testrun.json -- -cover ./... -args -test.gocoverdir="$PWD/covdata/unit"
    - name: Report
      uses: mcous/go-test-annotations@c88dae7c338c628e850685a0e8aa6a8fc2f4685d
      # Only upload annotations from 1.24 -- we can manually go and look for other failures
      if: ${{ !cancelled() && matrix.version == '1.24' }}
      with:
        test-report: testrun.json
    - name: Merge coverage
      if: ${{ !cancelled() && matrix.version == '1.24' && env.ACT != 'true' }}
      run: |
        go tool covdata textfmt -i=./covdata/gen,./covdata/unit -o cover.out
        # We need to make coveralls happy with the merged file output
        sed -i  -e "s#${PWD}/#github.com/ashb/oapi-resty-codegen/#" cover.out
    - name: Report Coveralls
      uses: coverallsapp/github-action@v2
      # Don't run Coveralls locally when we are invoked via `act`
      if: ${{ !cancelled() && matrix.version == '1.24' && env.ACT != 'true' }}
      with:
        file: cover.out

